= RHOSP18 - Provision Control Plane Services and Manage Data Plane Nodes
:navtitle: Home

Welcome to this quick course on _Provision Control Plane Services and Manage Data Plane Nodes in RHOSP18_. 

Red Hat OpenStack Services on OpenShift (RHOSO) is the next generation of Red Hat OpenStack Platform.
Click https://www.redhat.com/en/blog/red-hat-openstack-services-openshift-next-generation-red-hat-openstack-platform[here] for more information.

This course provides step-by-step instructions for deploying a Red Hat OpenStack Platform 18 cluster. 

The course includes a hands-on lab with a pre-deployed Red Hat OpenShift Container Platform (RHOCP) cluster. 
You will deploy Red Hat OpenStack control plane services on top of the RHOCP cluster. 
Additionally, this training covers the steps to provision a pre-deployed compute node that acts as the data plane of your RHOSP deployment. 
You will attach the pre-deployed compute node to the RHOSP18 control plane running on the OCP cluster.


== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Pedro Navarro Perez
* Fernando Lozano
* Ashish Shah

== Classroom Environment for Red Hat Associates

Continue using the https://demo.redhat.com/catalog?item=babylon-catalog-prod/community-content.com-nextgen-osp.prod&utm_source=webapp&utm_medium=share-link[Red Hat OpenStack Services on OpenShift Dev Preview Demo] lab for hands-on activity for this course.

NOTE: The catalog may take approximately 2 hours to get provisioned.

== Prerequisites

* RHEL system administration: RHCSA (RH124, RH134)
* Local container management on RHEL with podman (RH134).
* Basic operation of OpenStack Services on OpenShift: OSP-Operations-I-1 and OSP-Operations-I-2. [or equivalent courses from OSP 16/17]
* Basic administration of OpenStack Services on OpenShift: OSP-Administration-I-1, OSP-Administration-I-2, and OSP-Administration-I-3.
* Datacenter networking concepts: ISO model, VLANs, firewalls, and Internet protocols, including but not limited to ICMP, IP, and HTTP.

== Objectives

* Traditional TripleO deployment verses deployment with OpenShift cluster.
* RHOSO deployment process overview.
* Pre-requisites for RHOSO deployment.
* Deploy control plane services on the RHOCP cluster.
* Verify functionality of control plane services.
* Deploy data plane node using RHOCP cluster.
* Verify functionality of data plane deployment.
* Verify RHOSP cluster function by deploying workload on it.
