= Configuring Network Attachment Definition

*Reference:* Step #7 on https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/18.0-dev-preview/html-single/deploying_red_hat_openstack_platform_18.0_development_preview_3_on_red_hat_openshift_container_platform/index#proc_preparing-RHOCP-for-RHOSP-network-isolation_preparing[the same link on the previous page] for Section 3.4. Preparing RHOCP for RHOSP network isolation.

. Copy sample configuration for the network-attachment-defination configuration from the same documentation url (step #8)
+
*or*
+
use the provided sample configuration file `single-nic-vlan-netattach.sample`.

. Create a copy of sample config to configure network attachment defination for your deployment.
+
[source,bash]
----
cp single-nic-vlan-netattach.sample osp-ng-netattach.yaml
----

. Edit the file with your preferred editor. 
+
[source,bash]
----
vi osp-ng-netattach.yaml
----

. Change the interface name and ipaddress as per your setup. Refer to network cofiguration table.
. Copy the ctlplane block and paste it at the bottom and change it for external network configuration with the relevant interface and ip addresses.

. Configure a *nad* resource for each isolated network to attach a service pod to the network:
+
[source,bash,role=execute]
----
oc apply -f osp-ng-netattach.yaml
----

. Verify the `network-attachment-definitions` created with the above command:
+
[source,bash,role=execute]
----
oc get network-attachment-definitions.k8s.cni.cncf.io -n openstack
----
+
.Sample Output
----
NAME          AGE
ctlplane      5s
external      5s
internalapi   5s
storage       5s
tenant        5s
----


