= Preparing RHOCP for RHOSP Network Isolation

Network confiuration for the nodes is facilated by the below operators.

*NMState operator* _facilitates network configuration for the nodes of the cluster._
`NodeNetworkConfigurationPolicy` offered by nmstate operator allows you to configure network settings on individual nodes in a network. 
This policy can be used to set network interfaces, routing tables, firewall rules, and other network-related settings. 

*Multus CNI plugin* _facilitates the network configuration for the pods running control plane services for the cluster._
`NetworkAttachmentDefinition` (NAD) is a feature offered by the Multus CNI (Container Network Interface) plugin. 
NAD is used to define network attachment points and states for network devices, allowing for automatic fencing and management of those devices. 

*MetalLB operator* _offers load blaancing service for OCP baremetal cluster._
`IPAddressPool` and `L2Advertisement` CRs offered by MetalLB operator facilitates IP advertisement from specified pools, ensuring efficient IP allocation to services and namespaces. 
By leveraging these custom resources, OpenShift facilitates efficient communication between nodes within the cluster, promoting seamless integration and performance optimization in networking-intensive environments.

FIXME: review the explanation above.

Please refer to the following table for the network configuration utilized in this deployment:

FIXME: review/change this table if required. also see if any google spreadsheet link can be provided for such configuration in the custom deployment.

[cols="1,1,1,1,1,1,1"]
|===
|Network name | VLAN | CIDR	| NetConfig allocation | Range	MetalLB IPAddressPool range	| nad ipam range | OCP worker nncp range

| ctlplane
| n/a
| 172.22.0.0/24
| 172.22.0.100 - 172.22.0.120
| 172.22.0.80-172.22.0.90
| 172.22.0.30 - 172.22.0.70
| 172.22.0.10 - 172.22.0.20

| internalapi
| 20
| 172.17.0.0/24
| 172.17.0.100 - 172.17.0.250
| 172.17.0.80-172.17.0.90
| 172.17.0.30 - 172.17.0.70
| 172.17.0.10 - 172.17.0.20

| storage
| 21
| 172.18.0.0/24
| 172.18.0.100 - 172.18.0.250
| 172.18.0.80-172.18.0.90
| 172.18.0.30 - 172.18.0.70
| 172.18.0.10 - 172.18.0.20

| tenant
| 22
| 172.19.0.0/24
| 172.19.0.100 - 172.19.0.250
| 172.19.0.80-172.19.0.90
| 172.19.0.30 - 172.19.0.70
| 172.19.0.10 - 172.19.0.20

| external
| n/a
| 192.168.123.0/24
| 192.168.123.61 - 192.168.123.90
| 192.168.122.80 - 192.168.122.90
| 192.168.123.60 - 192.168.123.110
|  

|===


We will create the required configuration files from scratch by referring to the sample configuration provided in the product documentation:

https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/18.0-dev-preview/html-single/deploying_red_hat_openstack_platform_18.0_development_preview_3_on_red_hat_openshift_container_platform/index#doc-wrapper[Deploying Red Hat OpenStack Platform 18.0 Development Preview 3 on Red Hat OpenShift Container Platform]

Sample configuration files captured from the product documentation are provided, files with extension `\*.sample`. 
Additionally, preconfigured YAML files, named with the prefix `osp-ng-\*`, are made available in the git repository.

IMPORTANT: The pre-configured YAML files are included for your convenience. 
However, we recommend creating your own YAML files using the sample configuration from the product documentation. 
You may use the provided sample configuration in the lab to avoid copy-pasting from the documentation and refer to the pre-configured files for reference as needed.

NOTE: For deployments in other environments, consider creating a table listing the necessary network isolation and their corresponding IP/subnet ranges. 
This will help streamline the process.

. Clone the Files Repo.
+
In the bastion terminal, clone the repo and change directory to the files that we will use later in the lab.
+
[source,bash]
----
git clone https://github.com/RedHatQuickCourses/rhoso-deploy-files.git
cd rhoso-deploy-files
----

NOTE: For the following steps, we are referring to https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/18.0-dev-preview/html-single/deploying_red_hat_openstack_platform_18.0_development_preview_3_on_red_hat_openshift_container_platform/index#proc_preparing-RHOCP-for-RHOSP-network-isolation_preparing[Section 3.4. Preparing RHOCP for RHOSP network isolation] from _Deploying Red Hat OpenStack Platform 18.0 Development Preview 3 on Red Hat OpenShift Container Platform guide_. 

TIP: Sample files are made available for your convenience so as to avoid copy-paste of sample configuration from the product documentation. If required, you may open the above link in another tab for handy reference.